
spring:
  data:
    mongodb:
        username: cross
        authentication-database: admin
        password: cross
        host: 127.0.0.1
        database: test
        port: 27017
        repositories: 
            enabled: true
    rest:
      base-path: /api/v1
  jackson:
    time-zone: GMT-4
  jpa:
    open-in-view : false
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
logging:
    level:
        root: warn
        com.cross: INFO
        org.springframework.boot: warn
        org.hibernate.SQL: debug
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server:
    port: 8080
    servlet:
      context-path: /api/v1